# Generated by Django 3.2.16 on 2023-02-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0085_alter_resourcebase_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='QGIS_Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zip_file', models.FileField(upload_to='pages/')),
                ('directory_path', models.CharField(blank=True, max_length=500, null=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.resourcebase')),
            ],
        ),
    ]
