# Generated by Django 3.2.16 on 2023-02-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgis_maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qgis_maps',
            options={'verbose_name_plural': 'QGIS_Maps'},
        ),
        migrations.AddField(
            model_name='qgis_maps',
            name='folder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
