import re
from urllib.parse import urlencode

# Middleware currently not in use! extend_info_panel.html is now making a second request to get the metadata

class AppendMetadataMiddleware:
    """
    Middleware class that appends the 'metadata' include parameter to requests for specific API paths.

    This middleware checks if the request path starts with one of the specified prefixes, and if so,
    appends the 'metadata' include parameter to the request GET parameters.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        """
        Process the request and add the 'metadata' include parameter if the request path starts with a specified prefix.

        :param request: The incoming request object.
        :return: The response generated by the get_response function.
        """
        path_regex = re.compile(r'^/api/v2/(resources|datasets|maps|documents|geoapps)/\d+/?')
        if path_regex.match(request.path):
            # Create a mutable copy of the GET parameters
            params = request.GET.copy()
            
            # Get existing 'include[]' parameters
            includes = params.getlist("include[]")
            
            # Add 'metadata' if it's not already included
            if "metadata" not in includes:
                params.appendlist("include[]", "metadata")
            
            # Reconstruct the full query string
            request.META['QUERY_STRING'] = urlencode(params, doseq=True)

        return self.get_response(request)
