# Generated by Django 2.2.16 on 2021-05-07 08:38

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasecase',
            name='publication',
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='publication_link',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
