# Generated by Django 2.2.16 on 2021-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0002_auto_20210507_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='reference_images',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
