# Generated by Django 2.2.16 on 2021-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0003_auto_20210507_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_individualid',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_site',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_tombid',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='chronology',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='dna_analyses_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='storage_place_freetext',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
