# Generated by Django 2.2.16 on 2021-05-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0004_auto_20210507_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasecase',
            name='archaeological_site',
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='gazId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='gaz_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='site',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
