# Generated by Django 2.2.20 on 2021-06-14 09:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0005_auto_20210510_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='bone_relations',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='inventory',
            field=jsonfield.fields.JSONField(),
        ),
    ]
