# Generated by Django 2.2.20 on 2021-07-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0006_auto_20210614_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasecase',
            old_name='geoserver_id',
            new_name='uuid',
        ),
    ]
