# Generated by Django 2.2.20 on 2021-08-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0009_remove_diseasecase_geoserver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bone',
            name='svgid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
