# Generated by Django 2.2.20 on 2022-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0013_diseasecase_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='comment',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='references',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
