# Generated by Django 2.2.20 on 2022-01-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0016_auto_20220131_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=5)),
            ],
        ),
    ]
