# Generated by Django 2.2.20 on 2022-01-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0017_institutlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasecase',
            name='storage_condition',
        ),
    ]
