# Generated by Django 2.2.20 on 2022-01-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0018_remove_diseasecase_storage_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasecase',
            name='publication_link',
        ),
    ]
