# Generated by Django 2.2.20 on 2022-01-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0019_remove_diseasecase_publication_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='storage_place',
            field=models.CharField(choices=[('institution_1', 'Institution 1'), ('institution_2', 'Institution 2'), ('institution_3', 'Institution 3'), ('unknown', 'UNKNOWN')], max_length=1200),
        ),
    ]
