# Generated by Django 2.2.20 on 2022-01-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0021_helps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Helps',
            new_name='Helper',
        ),
    ]
