# Generated by Django 2.2.20 on 2022-02-02 18:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0030_auto_20220202_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='dating_method',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='storage_place',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
