# Generated by Django 2.2.20 on 2022-10-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0032_auto_20220412_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_burial_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('multiple', 'Multiple'), ('unknown', 'Unknown')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_funery_context',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('unknown', 'Unknown')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='dna_analyses',
            field=models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful'), ('absent', 'Absent'), ('unknown', 'Unknown')], max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='sex',
            field=models.CharField(choices=[('f', 'F'), ('f?', 'F?'), ('unknown', 'Unknown'), ('m', 'M'), ('m?', 'M?')], max_length=200),
        ),
        migrations.AddField(
            model_name='diseaselibrary',
            name='disease_alias',
            field=models.ManyToManyField(blank=True, related_name='diseasea_alias', to='daard_database.DiseaseAlias'),
        ),
    ]
