# Generated by Django 2.2.20 on 2022-10-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0035_auto_20221011_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='differential_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseasealias',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='aliases', to='daard_database.DiseaseLibrary'),
        ),
    ]
