# Generated by Django 3.2.21 on 2023-11-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0037_alter_diseasecase_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoneChangeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bone_change_images/')),
                ('bone_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='daard_database.bonechange')),
            ],
        ),
    ]
