# Generated by Django 3.2.21 on 2023-11-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0038_bonechangefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='chronology_method',
            field=models.CharField(blank=True, help_text='Used method chronology', max_length=400),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='sex_method',
            field=models.CharField(blank=True, help_text='Used method sex', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='size_from',
            field=models.FloatField(blank=True, help_text='Body size in cm (e.g., 177.10)', null=True),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='size_method',
            field=models.CharField(blank=True, help_text='Used method size', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='size_to',
            field=models.FloatField(blank=True, help_text='Body size in cm (e.g., 181.10)', null=True),
        ),
    ]
