# Generated by Django 3.2.21 on 2023-11-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0039_auto_20231127_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasecase',
            old_name='sex_method',
            new_name='sex_freetext',
        ),
    ]
