# Generated by Django 3.2.21 on 2023-11-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0040_rename_sex_method_diseasecase_sex_freetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='date_last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
