# Generated by Django 3.2.21 on 2023-11-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0041_auto_20231129_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasecase',
            name='age',
        ),
        migrations.RemoveField(
            model_name='diseasecase',
            name='chronology_method',
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='age_estimation_method',
            field=models.CharField(blank=True, help_text='Used method age', max_length=400),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='narrower_age_class_freetext',
            field=models.CharField(blank=True, help_text='Narrower age class freetext', max_length=400),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='sex_freetext',
            field=models.CharField(blank=True, help_text='Method used for sex determination', max_length=400, null=True),
        ),
    ]
