# Generated by Django 2.2.28 on 2024-01-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daard_database', '0042_auto_20231130_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasecase',
            old_name='size_method',
            new_name='size_freetext',
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='age_class',
            field=models.CharField(choices=[('Foetus', 'Fetus'), ('Infans', 'Infans'), ('Adolescent', 'Adolescent'), ('Early Adult', 'Early Adult'), ('Late Adult', 'Late Adult'), ('Senile', 'Senile'), ('0–3', '0 – 3 years'), ('4–6', '4 – 6 years'), ('7–12', '7 – 12 years'), ('13–20', '13 – 20 years'), ('21–35', '21 – 35 years'), ('36–50', '36 – 50 years'), ('50+', '50 + years'), ('Unknown', 'Unknown')], max_length=200),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='archaeological_funery_context',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('unknown', 'Unknown'), ('commingled', 'Commingled')], max_length=400, null=True),
        ),
    ]
